# Generated by Django 5.1.7 on 2025-03-31 20:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mapguess',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mapguess',
            name='distance_to_target',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapguess',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mapguess',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapguess',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportguess',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transportguess',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportguess',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapguess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transportguess',
            name='transport',
            field=models.CharField(choices=[('car', 'Voiture'), ('train', 'Train'), ('bus', 'Bus'), ('plane', 'Avion'), ('bike', 'Vélo'), ('walk', 'Marche'), ('other', 'Autre')], max_length=10),
        ),
        migrations.CreateModel(
            name='GameEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('evaluated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
