# Generated by Django 5.1.7 on 2025-03-31 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_mapguess_created_at_mapguess_distance_to_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapguess',
            name='city_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
