# Generated by Django 5.1.7 on 2025-04-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_mapguess_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportguess',
            name='transport',
            field=models.CharField(choices=[('car', 'Voiture'), ('train', 'Train'), ('bus', 'Bus'), ('plane', 'Avion'), ('ship', 'Bateau'), ('walk', 'Marche')], max_length=10),
        ),
    ]
