# Generated by Django 5.1.7 on 2025-04-01 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_transportguess_transport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportguess',
            old_name='is_correct',
            new_name='is_verified',
        ),
    ]
