# Generated by Django 5.1.7 on 2025-04-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_rename_is_correct_transportguess_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportguess',
            name='transport',
            field=models.CharField(choices=[('car', 'Voiture'), ('train', 'Train'), ('bus', 'Bus'), ('plane', 'Avion'), ('ship', 'Bateau'), ('walk', 'Marche'), ('bike', 'Vélo'), ('subway', 'Métro/RER')], max_length=10),
        ),
    ]
