# Generated by Django 5.1.7 on 2025-04-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_transportguess_transport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameevaluation',
            name='feedback',
        ),
        migrations.AddField(
            model_name='gameevaluation',
            name='poll_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameevaluation',
            name='total_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameevaluation',
            name='transport_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
