# Generated by Django 5.1.7 on 2025-04-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_remove_gameevaluation_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportguess',
            name='transport',
        ),
        migrations.AddField(
            model_name='transportguess',
            name='transports',
            field=models.JSONField(default=list),
        ),
    ]
