# Generated by Django 5.1.7 on 2025-04-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_remove_transportguess_transport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapguess',
            name='distance_to_target',
        ),
        migrations.RemoveField(
            model_name='mapguess',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='mapguess',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='mapguess',
            name='score',
        ),
        migrations.RemoveField(
            model_name='transportguess',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='transportguess',
            name='score',
        ),
        migrations.AddField(
            model_name='mapguess',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transportguess',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
