# Generated by Django 5.1.7 on 2025-04-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_remove_mapguess_distance_to_target_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameevaluation',
            name='poll_rank',
        ),
        migrations.RemoveField(
            model_name='gameevaluation',
            name='transport_rank',
        ),
    ]
