# Generated by Django 5.1.7 on 2025-04-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_rename_total_rank_gameevaluation_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportguess',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
