# Generated by Django 5.1.7 on 2025-04-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_transportguess_total_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportguess',
            name='total_score',
        ),
    ]
