# Generated by Django 5.1.7 on 2025-04-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_remove_transportguess_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapguess',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transportguess',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
