# Generated by Django 5.1.7 on 2025-04-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_mapguess_total_score_transportguess_total_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameEvaluation',
        ),
    ]
